name: oguk-dev
channels:
- conda-forge
dependencies:
- python>=3.7.7
- ipython
- setuptools
- mkl>=2020.2
- psutil
- scipy>=1.5.0
- pandas>=1.0.5
- matplotlib
- dask==2.30.0
- dask-core==2.30.0
- distributed==2.30.1
- paramtools>=0.15.0
- openpyxl
- sphinx>=3.1.2
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- black
- pre-commit
- taxcalc
- pip:
  - jupyter-book>=0.8.0
  - git+https://github.com/PSLmodels/OG-USA.git
  - git+https://github.com/nikhilwoodruff/openfisca-core
  - git+https://github.com/nikhilwoodruff/frs
  - git+https://github.com/PSLmodels/openfisca-uk
  - git+https://github.com/PSLmodels/microdf
